#############################################################################
# Makefile for building: MapColorFinalGUI
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue May 22 01:53:56 2012
# Project:  MapColorFinalGUI.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile MapColorFinalGUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = arrow.cpp \
		ellipseitem.cpp \
		main.cpp \
		mainscene.cpp \
		mainwindow.cpp \
		mapcolorga.cpp \
		drawbrmap.cpp moc_mainscene.cpp \
		moc_mainwindow.cpp
OBJECTS       = arrow.o \
		ellipseitem.o \
		main.o \
		mainscene.o \
		mainwindow.o \
		mapcolorga.o \
		drawbrmap.o \
		moc_mainscene.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MapColorFinalGUI.pro
QMAKE_TARGET  = MapColorFinalGUI
DESTDIR       = 
TARGET        = MapColorFinalGUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MapColorFinalGUI.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile MapColorFinalGUI.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile MapColorFinalGUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MapColorFinalGUI1.0.0 || $(MKDIR) .tmp/MapColorFinalGUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MapColorFinalGUI1.0.0/ && $(COPY_FILE) --parents arrow.h ellipseitem.h mainscene.h mainwindow.h mapcolorga.h .tmp/MapColorFinalGUI1.0.0/ && $(COPY_FILE) --parents arrow.cpp ellipseitem.cpp main.cpp mainscene.cpp mainwindow.cpp mapcolorga.cpp drawbrmap.cpp .tmp/MapColorFinalGUI1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/MapColorFinalGUI1.0.0/ && (cd `dirname .tmp/MapColorFinalGUI1.0.0` && $(TAR) MapColorFinalGUI1.0.0.tar MapColorFinalGUI1.0.0 && $(COMPRESS) MapColorFinalGUI1.0.0.tar) && $(MOVE) `dirname .tmp/MapColorFinalGUI1.0.0`/MapColorFinalGUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MapColorFinalGUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainscene.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainscene.cpp moc_mainwindow.cpp
moc_mainscene.cpp: ellipseitem.h \
		mainscene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainscene.h -o moc_mainscene.cpp

moc_mainwindow.cpp: ellipseitem.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

arrow.o: arrow.cpp arrow.h \
		ellipseitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrow.o arrow.cpp

ellipseitem.o: ellipseitem.cpp ellipseitem.h \
		arrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ellipseitem.o ellipseitem.cpp

main.o: main.cpp mainwindow.h \
		ellipseitem.h \
		mapcolorga.h \
		mainscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainscene.o: mainscene.cpp mainscene.h \
		ellipseitem.h \
		arrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainscene.o mainscene.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ellipseitem.h \
		ui_mainwindow.h \
		mainscene.h \
		mapcolorga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mapcolorga.o: mapcolorga.cpp mapcolorga.h \
		mainscene.h \
		ellipseitem.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapcolorga.o mapcolorga.cpp

drawbrmap.o: drawbrmap.cpp mainwindow.h \
		ellipseitem.h \
		ui_mainwindow.h \
		mainscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawbrmap.o drawbrmap.cpp

moc_mainscene.o: moc_mainscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainscene.o moc_mainscene.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

